### ISSUE TITLE
fix: config 폴더의 yaml 파일로 설정값 설정하기

### ISSUE THREAD

**Issue by refigo** [42Mogle/42-mogle-backend#64]
## TODO
- [x] Config 모듈 설치, 세팅
- [x] 설정파일 세팅
	- [x] default.yml
	- [x] development.yml
	- [x] production.yml
- [x] 설정값 세팅
	- [x] app
	- [x] database
	- [x] jwt

## Config files
```yaml
# default.yaml

server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: '42mogle-default'

jwt:
  expiresIn: 216000
```

``` yaml
# development.yaml

db:
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  synchronize: true

jwt:
  secret: 'secret42mogle13'
```

```yaml
# production.yaml

db:
  synchronize: false
```

## Usage

```typescript
import * as config from 'config';

const dbConfig = config.get('db');

// example
username = dbConfig.username;
```
